name: Get nice price

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        make venv

    - name: Get DL scan
      run: |
        make dl_scan

    - name: Get Alpha scan
      run: |
        make alpha_scan

    - name: Get nice price
      run: |
        make price

    - name: Get nice price
      run: |
        mkdir -p artifacts
        cp alphaspel_cards/* artifacts
        cp dragonslair_cards/* artifacts
        cp scryfall_cards/small_cards_* artifacts
        cp nice_prices/* artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: artifacts