name: Get nice price

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
    
  push:
    branches:
      - 'main'

jobs:
  # run:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python 3.12
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: '3.12'

  #   - name: Install dependencies
  #     run: |
  #       make venv

  #   - name: Get DL scan
  #     run: |
  #       make dl_scan

  #   - name: Get Alpha scan
  #     run: |
  #       make alpha_scan

  #   - name: Get nice price
  #     run: |
  #       make price

  #   - name: Get nice price
  #     run: |
  #       mkdir -p artifacts
  #       cp alphaspel_cards/* artifacts
  #       cp dragonslair_cards/* artifacts
  #       cp scryfall_cards/small_cards_* artifacts
  #       cp nice_prices/* artifacts

  #   - name: Upload Artifacts
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: results
  #       path: artifacts


  scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scan_type: ['dl_scan_short', 'alpha_scan_short']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: make venv

    - name: Run ${{ matrix.scan_type }} scan
      run: make ${{ matrix.scan_type }}

    - name: Upload scan Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ matrix.scan_type == 'dl_scan_short' }}
      with:
        name: ${{ matrix.scan_type }}
        path: dragonslair_cards

    - name: Upload scan Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ matrix.scan_type == 'alpha_scan_short' }}
      with:
        name: ${{ matrix.scan_type }}
        path: alphaspel_cards

  price:
    needs: scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create dirs
      run: |
        mkdir dragonslair_cards
        mkdir alphaspel_cards

    - name: Download DL artifacts
      uses: actions/download-artifact@v2
      with:
        name: dl_scan_short
        path: dragonslair_cards

    - name: Unzip DL artifacts
      run: unzip dragonslair_cards/*.zip -d dragonslair_cards

    - name: Download Alphaspel artifacts
      uses: actions/download-artifact@v2
      with:
        name: alpha_scan_short
        path: alphaspel_cards

    - name: Unzip Alphaspel artifacts
      run: unzip alphaspel_cards/*.zip -d alphaspel_cards

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: make venv

    - name: Get nice price
      run: make price

    - name: Get nice price
      run: |
        mkdir -p artifacts
        cp scryfall_cards/small_cards_* artifacts
        cp nice_prices/* artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nice_prices
        path: artifacts